
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "payslipSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PayslipSoap {


    /**
     * 
     * @param encryptedempcode
     * @param encryptedmonth
     * @param encryptedyear
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/getPaySlip")
    @WebResult(name = "getPaySlipResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "getPaySlip", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPaySlip")
    @ResponseWrapper(localName = "getPaySlipResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPaySlipResponse")
    public String getPaySlip(
        @WebParam(name = "encryptedempcode", targetNamespace = "http://tempuri.org/")
        String encryptedempcode,
        @WebParam(name = "encryptedmonth", targetNamespace = "http://tempuri.org/")
        String encryptedmonth,
        @WebParam(name = "encryptedyear", targetNamespace = "http://tempuri.org/")
        String encryptedyear);

}
