
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "payslip", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://164.100.213.134/MCSevice/payslip.asmx?WSDL")
public class Payslip
    extends Service
{

    private final static URL PAYSLIP_WSDL_LOCATION;
    private final static WebServiceException PAYSLIP_EXCEPTION;
    private final static QName PAYSLIP_QNAME = new QName("http://tempuri.org/", "payslip");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://164.100.213.134/MCSevice/payslip.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PAYSLIP_WSDL_LOCATION = url;
        PAYSLIP_EXCEPTION = e;
    }

    public Payslip() {
        super(__getWsdlLocation(), PAYSLIP_QNAME);
    }

    public Payslip(WebServiceFeature... features) {
        super(__getWsdlLocation(), PAYSLIP_QNAME, features);
    }

    public Payslip(URL wsdlLocation) {
        super(wsdlLocation, PAYSLIP_QNAME);
    }

    public Payslip(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PAYSLIP_QNAME, features);
    }

    public Payslip(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Payslip(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PayslipSoap
     */
    @WebEndpoint(name = "payslipSoap")
    public PayslipSoap getPayslipSoap() {
        return super.getPort(new QName("http://tempuri.org/", "payslipSoap"), PayslipSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PayslipSoap
     */
    @WebEndpoint(name = "payslipSoap")
    public PayslipSoap getPayslipSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "payslipSoap"), PayslipSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PAYSLIP_EXCEPTION!= null) {
            throw PAYSLIP_EXCEPTION;
        }
        return PAYSLIP_WSDL_LOCATION;
    }

}
