DROP TABLE IF EXISTS eg_ws_savebilling;
CREATE TABLE eg_ws_savebilling
(
  id character varying(64) not null,
 	ccCode          character varying    ,
	divSdiv          character varying ,
	consumerCode     character varying ,
	billCycle        character varying ,
	billGroup        character varying ,
	subGroup         character varying ,
	billType         character varying ,
	name             character varying ,
	address          character varying ,
	add1             character varying ,
	add2	         character varying ,
	add3	         character varying ,
	add4	         character varying ,
	add5	         character varying ,
	cessCharge	     character varying ,
	netAmount	     character varying ,
	grossAmount      character varying ,
	surcharge	     character varying ,
	totalNetAmount   character varying ,
	totalSurcharge   character varying ,
	totalGrossAmount character varying ,
	fixChargeCode    character varying ,
	fixCharge        character varying ,
	dueDateCash      character varying ,
	dueDateCheque    character varying ,
	status           character varying ,
	billId           character varying ,
	paymentId        character varying ,
	paymentStatus    character varying ,
  createdby character varying(64),
  lastmodifiedby character varying(64),
  createdtime bigint,
  lastmodifiedtime bigint,
  CONSTRAINT eg_ws_savebilling_pkey PRIMARY KEY (id)
);

