ALTER TABLE cs_ep_property_details_v1
ADD COLUMN IF NOT EXISTS house_number CHARACTER VARYING (256),
ADD COLUMN IF NOT EXISTS mohalla CHARACTER VARYING (256),
ADD COLUMN IF NOT EXISTS village CHARACTER VARYING (256);
