CREATE TABLE public.rti_ministry_master (
	ministry_code varchar(5) NOT NULL,
	ministry_name varchar(200) NULL,
	CONSTRAINT rti_ministry_master_pkey PRIMARY KEY (ministry_code)
);

INSERT INTO public.rti_ministry_master (ministry_code,ministry_name) VALUES 
('3421','UT Chandigarh- Cooperative Societies')
,('3418','UT Chandigarh- Agriculture Department')
,('3430','UT Chandigarh- Planning Evaluation Organization')
,('3419','UT Chandigarh- Agriculture Marketing Board')
,('3699','Market Committee')
,('1576','UT Chandigarh- Urban Planning (Architect & Town Planning)')
,('3393','UT Chandigarh- Planning & Evaluation Organisation')
,('3391','UT Chandigarh- Cultural Affairs')
,('1554','UT Chandigarh- Labour')
,('1535','UT Chandigarh- Vigilance')
,('1586','UT Chandigarh- Chandigrh College of Engineering Technology (Degree Wing)')
,('1540','UT Chandigarh- Govt. College of Arts')
,('1814','UT Chandigarh- Home Guards')
,('1570','UT Chandigarh- Printing & Stationery')
,('3566','UT Chandigarh- Deputy Commissioner  & District Magistrate')
,('1533','UT Chandigarh- School Education')
,('1565','UT Chandigarh- Public Relations')
,('1558','UT Chandigarh- Prisons')
,('1579','UT Chandigarh- Chandigarh Child Women Development Corporation Limited')
,('1585','UT Chandigarh- Chandigarh College of Architecture')
,('2140','UT Chandigarh- Local Audit')
,('1587','UT Chandigarh- Govt. Museum & Art Gallery')
,('1578','UT Chandigarh- Information Technology')
,('1580','UT Chandigarh- Chandigarh S.C.B.C. and Development Corporation Limited')
,('1589','UT Chandigarh- Forest  & Wildlife')
,('1567','UT Chandigarh- Higher Education')
,('1560','UT Chandigarh- Rural Development & Panchayats')
,('1562','UT Chandigarh- Statistical Cell')
,('1536','UT Chandigarh- State Legal Services Authority')
,('3598','UT Chandigarh- Sub Divisional Magistrate- Central (SDM-C)')
,('3599','UT Chandigarh- Sub Divisional Magistrate - South (SDM-S)')
,('1559','UT Chandigarh- Animal Husbandry & Fisheries')
,('1532','UT Chandigarh- Chandigarh Housing Board (CHB)')
,('1547','UT Chandigarh- Law & Prosecution')
,('1583','UT Chandigarh- Health')
,('3606','UT Chandigarh- Chandigarh Pollution Control Committee (CPCC)')
,('1720','UT Chandigarh- Secretariat & Home & Finance ')
,('1569','UT Chandigarh- Chandigarh Transport Undertaking (CTU) & Transport')
,('3428','UT Chandigarh- Industries')
,('3422','UT Chandigarh- Ayurveda, Yoga and Naturopathy, Unani Siddha & Homeopathy (AYUSH)')
,('3600','UT Chandigarh- Sub Divisional Magistrate- East  (SDM-E)')
,('3474','UT Chandigarh- Engineering')
,('3424','UT Chandigarh- Environment')
,('3603','UT Chandigarh- Health & Sanitation MOH (MCC)')
,('3425','UT Chandigarh- Estate Office')
,('3416','UT Chandigarh- Rent Controller Office')
,('3602','UT Chandigarh- Engineering (MCC)')
,('3604','UT Chandigarh- Administrative Wing (MCC)')
,('3427','UT Chandigarh- Hospitality')
,('3426','UT Chandigarh- Excise  & Taxation')
,('3423','UT Chandigarh- Election')
,('3568','UT Chandigarh- Red Cross Society')
,('3605','UT Chandigarh- House Allotment Committee')
,('1568','UT Chandigarh- Science & Technology & Renewable Energy')
,('1584','UT Chandigarh- Technical Education')
,('3601','UT Chandigarh- Fire & Emergency Services (MCC)')
,('1544','UT Chandigarh- State Transport Authority (STA)')
,('1809','UT Chandigarh- Zila Parishad')
,('1557','UT Chandigarh- Sports')
,('1545','UT Chandigarh- Tourism')
,('3432','UT Chandigarh- Zila Sainik Welfare Board')
,('3607','UT Chandigarh- Food & Supplies,Consumer Affairs & Legal Metrology')
,('1812','UT Chandigarh- Govt. Institute for Mentally Retarded Children (GRIID)')
,('1582','UT Chandigarh- Central Treasury')
,('1542','UT Chandigarh- Regional Employment Exchange')
,('3420','UT Chandigarh- Chandigarh Industrial Tourism Development Corporation  (CITCO)')
,('1546','UT Chandigarh- Police ')
,('1548','UT Chandigarh- Govt. Medical College & Hospital (GMCH 32)')
,('3417','UT Chandigarh- Agricultural Census')
,('1549','UT Chandigarh- Chandigarh State Consumer Disputes Redressal Commission')
,('1541','UT Chandigarh- Punjab Engineering College (PEC)')
,('3392','UT Chandigarh- ICDS Social Welfare')
,('1534','UT Chandigarh- Social Welfare & Women & Child Development')
,('3431','UT Chandigarh- Registring Licensing Authority')
;