CREATE TABLE public.nulm_suh_application_detail (
	suh_uuid varchar(256) NOT NULL,
	suh_id varchar(256) NULL,
	nulm_application_id varchar(64) NULL,
	name_of_shelter varchar(256) NULL,
	address varchar(256) NULL,
	shelter_background varchar(256) NULL,
	category varchar(256) NULL,
	weather_condition varchar(256) NULL,
	shelter_classification varchar(256) NULL,
	other_classification varchar(256) NULL,
	ownership varchar(256) NULL,
	operation_and_management_of_shelters varchar(256) NULL,
	area varchar(256) NULL,
	capacity varchar(256) NULL,
	is_constitution_of_shelter_management_committee bool NULL,
	constitution_of_shelter_management_committee_remark varchar(256) NULL,
	is_social_audit bool NULL,
	social_audit_remark varchar(256) NULL,
	is_linkage_to_central_govt_welfare_schemes bool NULL,
	linkage_to_central_govt_welfare_schemes_remark varchar(256) NULL,
	is_linkage_to_public_health_initiatives bool NULL,
	linkage_to_public_health_initiatives_remark varchar(256) NULL,
	is_linkage_to_other_govt_schemes bool NULL,
	linkage_to_other_govt_schemes_remark varchar(256) NULL,
	is_linkage_to_local_community bool NULL,
	linkage_to_local_community_remark varchar(256) NULL,
	is_linkage_to_social_workers_and_philanthropists bool NULL,
	linkage_to_social_workers_and_philanthropists_remark varchar(256) NULL,
	is_user_charges bool NULL,
	user_charges_remark varchar(256) NULL,
	is_iec_and_promotional_initiatives bool NULL,
	iec_and_promotional_initiatives_remark varchar(256) NULL,
	is_quarterly_reporting bool NULL,
	quarterly_reporting_remark varchar(256) NULL,
	is_visits bool NULL,
	visits_remark varchar(256) NULL,
	address_picture json NULL,
	program_picture json NULL,
	document_attachment json NULL,
	remark varchar(256) NULL,
	application_status varchar(256) NULL,
	tenant_id varchar(256) NOT NULL,
	is_active bool NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	assigned_to varchar(64) NULL,
	CONSTRAINT nulm_suh_application_detail_pkey PRIMARY KEY (suh_uuid),
	CONSTRAINT fk_nulm_suh_application_detail FOREIGN KEY (assigned_to) REFERENCES nulm_organization(organization_uuid)
);