CREATE TABLE nulm_suh_record_maintenance (
	suh_uuid varchar(256) NULL,
	record_uuid varchar(256) NOT NULL,
	is_asset_inventory_register bool NULL,
	asset_inventory_register_remark varchar(256) NULL,
	is_acount_register bool NULL,
	acount_register_remark varchar(256) NULL,
	is_attendance_register_of_staff bool NULL,
	attendance_register_of_staff_remark varchar(256) NULL,
	is_shelter_management_committee_register bool NULL,
	shelter_management_committee_register_remark varchar(256) NULL,
	is_personnel_and_salary_register bool NULL,
	personnel_and_salary_register_remark varchar(256) NULL,
	is_housekeeping_and_maintenance_register bool NULL,
	housekeeping_and_maintenance_register_remark varchar(256) NULL,
	is_complaint_and_suggestion_register bool NULL,
	complaint_and_suggestion_register_remark varchar(256) NULL,
	is_visitor_register bool NULL,
	visitor_register_remark varchar(256) NULL,
	is_profile_register bool NULL,
	profile_register_remark varchar(256) NULL,
	tenant_id varchar(256) NOT NULL,
	is_active bool NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	CONSTRAINT nulm_suh_record_maintenance_pkey PRIMARY KEY (record_uuid)
);