CREATE TABLE public.nulm_smid_shg_detail (
	shg_uuid varchar(256) NOT NULL,
	shg_id varchar(256) NOT NULL,
	"name" varchar(256) NOT NULL,
	"type" varchar(256) NULL,
	groups_nominated_by varchar(256) NULL,
	formed_through varchar(256) NULL,
	status varchar(256) NOT NULL,
	address varchar(256) NULL,
	contact_no varchar(256) NULL,
	date_of_formation timestamp NULL,
	account_no varchar(256) NULL,
	date_of_opening_account timestamp NULL,
	bank_name varchar(256) NULL,
	branch_name varchar(256) NULL,
	main_activity varchar(256) NULL,
	remark varchar(256) NULL,
	tenant_id varchar(256) NULL,
	is_active bool NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	CONSTRAINT nulm_smid_shg_detail_pkey PRIMARY KEY (shg_uuid)
);