CREATE TABLE nulm_sep_application_detail (
	application_uuid varchar(64) NOT NULL,
	application_id varchar(64) NOT NULL,
	nulm_application_id varchar(64) NULL,
	application_status varchar(64) NULL,
	"name" varchar(255) NULL,
	gender varchar(255) NULL,
	age int4 NULL,
	dob timestamp NULL,
	adhar_no varchar(20) NULL,
	mother_name varchar(255) NULL,
	father_or_husband_name varchar(255) NULL,
	occupation varchar(255) NULL,
	address varchar(255) NULL,
	contact varchar(255) NULL,
	since_how_long_in_chandigarh varchar(255) NULL,
	qualification varchar(255) NULL,
	category varchar(255) NULL,
	is_urban_poor bool NULL,
	is_minority bool NULL,
	is_handicapped bool NULL,
	is_loan_from_bankinginstitute bool NULL,
	is_repayment_made bool NULL,
	bpl_no varchar(255) NULL,
	minority varchar(255) NULL,
	type_of_business_to_be_started varchar(255) NULL,
	previous_experience varchar(255) NULL,
	place_of_work varchar(255) NULL,
	no_of_family_members varchar(255) NULL,
	project_cost numeric NULL,
	loan_amount numeric NULL,
	recommended_by varchar(255) NULL,
	representative_name varchar(255) NULL,
	representative_address varchar(255) NULL,
	tenant_id varchar(256) NULL,
	is_active bool NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	remark varchar(256) NULL,
	account_name varchar(255) NULL,
	bank_name varchar(255) NULL,
	branch_name varchar(255) NULL,
	is_disability_certificate_available bool NULL,
	task_committee_approved_amount varchar(255) NULL,
	task_committee_remark varchar(255) NULL,
	task_committee_action_date timestamp NULL,
	task_committee_status varchar(255) NULL,
	committee_bank_name varchar(255) NULL,
	committee_branch_name varchar(255) NULL,
	application_forwarded_on_date timestamp NULL,
	sanction_date timestamp NULL,
	sanction_remarks varchar(255) NULL,
	CONSTRAINT application_id UNIQUE (application_id),
	CONSTRAINT nulm_sep_application_detail_pkey PRIMARY KEY (application_uuid)
);