CREATE TABLE public.nulm_suh_facilities_maintenance (
	suh_uuid varchar(256) NULL,
	facility_uuid varchar(256) NOT NULL,
	is_bedding bool NULL,
	bedding_remark varchar(256) NULL,
	is_washing_of_linen bool NULL,
	washing_of_linen_remark varchar(256) NULL,
	is_cleaning_of_premises bool NULL,
	cleaning_of_premise_remark varchar(256) NULL,
	is_recreation_facilities bool NULL,
	recreation_facilities_remark varchar(256) NULL,
	is_drinking_water bool NULL,
	drinking_water_remark varchar(256) NULL,
	is_meals bool NULL,
	meals_remark varchar(256) NULL,
	is_locker_for_inmates bool NULL,
	locker_for_inmates_remark varchar(256) NULL,
	is_fire_safety_measure bool NULL,
	fire_safety_measure_remark varchar(256) NULL,
	is_office_set_up bool NULL,
	office_set_up_remark varchar(256) NULL,
	is_first_aid_kit_and_training_to_staff bool NULL,
	first_aid_kit_and_training_to_staff_remark varchar(256) NULL,
	is_display_of_emergency_numbers bool NULL,
	display_of_emergency_numbers_remark varchar(256) NULL,
	is_toilet bool NULL,
	toilet_remark varchar(256) NULL,
	facility_picture json NULL,
	tenant_id varchar(256) NOT NULL,
	is_active bool NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	CONSTRAINT nulm_suh_facilities_maintenance_pkey PRIMARY KEY (facility_uuid)
);