CREATE TABLE nulm_susv_application_detail (
	application_uuid varchar(64) NOT NULL,
	application_id varchar(64) NOT NULL,
	nulm_application_id varchar(64) NULL,
	application_status varchar(64) NULL,
	name_of_applicant varchar(255) NULL,
	gender varchar(255) NULL,
	age int4 NULL,
	adhar_no varchar(20) NULL,
	mother_name varchar(255) NULL,
	father_or_husband_name varchar(255) NULL,
	permanent_address varchar(255) NULL,
	present_address varchar(255) NULL,
	mobile_no varchar(255) NULL,
	is_disability bool NULL,
	category varchar(255) NULL,
	qualification varchar(255) NULL,
	blood_group varchar(255) NULL,
	category_of_vending varchar(255) NULL,
	proposed_location_of_vending varchar(255) NULL,
	proposed_time_of_vending varchar(255) NULL,
	goverment_scheme varchar(255) NULL,
	name_of_nominee varchar(255) NULL,
	tenant_id varchar(256) NULL,
	remark varchar(256) NULL,
	is_active bool NULL,
	is_undertaking bool NULL,
	"date" timestamp NULL,
	place varchar(256) NULL,
	created_by varchar(64) NULL,
	created_time int8 NULL,
	last_modified_by varchar(64) NULL,
	last_modified_time int8 NULL,
	CONSTRAINT nulm_susv_application_detail_pkey PRIMARY KEY (application_uuid),
	CONSTRAINT susv_application_id UNIQUE (application_id)
);